language: python
install:
  - pip install -r requirements.txt
cache: pip
jobs:
  include:
    - stage: test
      script:
        - python -m pytest test
      python: '3.4'
    - stage: test
      script:
        - python -m pytest test
      python: '3.5'
    - stage: test
      script:
        - python -m pytest test
      python: '3.6'
    - stage: test
      script:
        - python -m pytest test
      python: '3.7'
      dist: xenial
      sudo: true     
    - stage: coverage
      python: '3.6'
      script:
        - python -m pytest --cov=./symspellpy
        - codecov
